add_newline = true


[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[âœ–](bold red) "
vicmd_symbol = "[V](bold green) "

[cmd_duration]
min_time = 1000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[conda]
symbol = "îœ¼ï   @ "
format = "[$symbol$environment](green) "

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "


[git_branch]
symbol = "îœ¥ "
truncation_length = 4
truncation_symbol = ""


[git_commit]
commit_hash_length = 4
tag_symbol = "îœˆ "
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "îŠ† Ã—${count}"
stashed = "ğŸ“¦ "
modified = "îœ© Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ï›€  Ã—${count}"
style = "red"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = false
format =  "[$hostname](blue) in "
disabled = false

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"


[package]
disabled = true

[python]
disabled = true
format = "[$symbol$version]($style) "
style = "bold green"

[nodejs]
format = "via [îœ˜ $version](bold green) "

[time]
use_12hr = true
time_format = "%r"
format = "î€€ $time($style) "
disabled = false

[username]
style_user = "blue"
format = "[$user]($style) @ "
disabled = false
show_always = true


[jobs]
symbol = "+ "
threshold = 2
style = "red"
